In [1]:
import tensorflow as tf

In [4]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [6]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


2025-03-03 12:53:54.872636: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [7]:
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)


tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [19]:
dataset = dataset.map(lambda x: X * 2)

for item in dataset:
    print(item)

tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14 16 18], shape=(10,), dtype=int32)
tf.Tensor([ 0  2  4  6  8 10 12 14

In [20]:
dataset = dataset.apply(tf.data.experimental.unbatch())

dataset = dataset.filter(lambda x: x < 10)

for item in dataset.take(3):
    print(item)


tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [24]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)

for item in dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)
